[2024-10-03T08:00:03.307+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-03T08:00:03.346+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v2.insert_into_table scheduled__2024-09-29T00:00:00+00:00 [queued]>
[2024-10-03T08:00:03.366+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v2.insert_into_table scheduled__2024-09-29T00:00:00+00:00 [queued]>
[2024-10-03T08:00:03.367+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-10-03T08:00:03.390+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-09-29 00:00:00+00:00
[2024-10-03T08:00:03.405+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=671) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-03T08:00:03.407+0000] {standard_task_runner.py:63} INFO - Started process 673 to run task
[2024-10-03T08:00:03.407+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v2', 'insert_into_table', 'scheduled__2024-09-29T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp3mf607pm']
[2024-10-03T08:00:03.410+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask insert_into_table
[2024-10-03T08:00:03.475+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_operator_v2.insert_into_table scheduled__2024-09-29T00:00:00+00:00 [running]> on host fb5d174c2391
[2024-10-03T08:00:03.580+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v2' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T00:00:00+00:00'
[2024-10-03T08:00:03.581+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-03T08:00:03.603+0000] {sql.py:276} INFO - Executing: 
            insert into dag_run (dt, dag_id) values ('2024-09-29','dag_with_postgres_operator_v2')
            
[2024-10-03T08:00:03.616+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-10-03T08:00:03.627+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-10-03T08:00:03.713+0000] {sql.py:470} INFO - Running statement: 
            insert into dag_run (dt, dag_id) values ('2024-09-29','dag_with_postgres_operator_v2')
            , parameters: None
[2024-10-03T08:00:03.717+0000] {sql.py:479} INFO - Rows affected: 1
[2024-10-03T08:00:03.720+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-03T08:00:03.735+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v2, task_id=insert_into_table, run_id=scheduled__2024-09-29T00:00:00+00:00, execution_date=20240929T000000, start_date=20241003T080003, end_date=20241003T080003
[2024-10-03T08:00:03.783+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-03T08:00:03.801+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-03T08:00:03.804+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
