[2024-10-03T08:09:10.824+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-03T08:09:10.856+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL_JsonData.unzip manual__2024-10-03T08:09:10.100089+00:00 [queued]>
[2024-10-03T08:09:10.867+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL_JsonData.unzip manual__2024-10-03T08:09:10.100089+00:00 [queued]>
[2024-10-03T08:09:10.868+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-10-03T08:09:10.885+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): unzip> on 2024-10-03 08:09:10.100089+00:00
[2024-10-03T08:09:10.893+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1346) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-03T08:09:10.893+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL_JsonData', 'unzip', 'manual__2024-10-03T08:09:10.100089+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/ETLProject/main.py', '--cfg-path', '/tmp/tmp5dcww30d']
[2024-10-03T08:09:10.894+0000] {standard_task_runner.py:63} INFO - Started process 1348 to run task
[2024-10-03T08:09:10.895+0000] {standard_task_runner.py:91} INFO - Job 90: Subtask unzip
[2024-10-03T08:09:10.946+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL_JsonData.unzip manual__2024-10-03T08:09:10.100089+00:00 [running]> on host fb5d174c2391
[2024-10-03T08:09:11.044+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_ETL_JsonData' AIRFLOW_CTX_TASK_ID='unzip' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T08:09:10.100089+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-03T08:09:10.100089+00:00'
[2024-10-03T08:09:11.045+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-03T08:09:11.057+0000] {logging_mixin.py:188} INFO - Lỗi khi giải nén file:[Errno 2] No such file or directory: '/downloads/og_item_impression.20240830_0840_3.json.gz'
[2024-10-03T08:09:11.058+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-03T08:09:11.059+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-03T08:09:11.069+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_ETL_JsonData, task_id=unzip, run_id=manual__2024-10-03T08:09:10.100089+00:00, execution_date=20241003T080910, start_date=20241003T080910, end_date=20241003T080911
[2024-10-03T08:09:11.110+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-03T08:09:11.131+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-03T08:09:11.134+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
